/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author tomasz
 */
public class CalculatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form OknoKalkulatora
     */
    public CalculatorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Title = new javax.swing.JLabel();
        jTextField_Arg1 = new javax.swing.JTextField();
        jTextField_Arg2 = new javax.swing.JTextField();
        jComboBox_action = new javax.swing.JComboBox<>();
        jTextField_result = new javax.swing.JTextField();
        jButton_calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        jLabel_Title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("Calculator");

        jTextField_Arg1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField_Arg1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField_Arg2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField_Arg2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jComboBox_action.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jComboBox_action.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/"}));

        jTextField_result.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField_result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton_calculate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_calculate.setText("=");
        jButton_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Arg1)
                            .addComponent(jButton_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_action, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Arg2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addComponent(jTextField_result))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Arg1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_action)
                            .addComponent(jTextField_Arg2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_result)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_action, jTextField_Arg1, jTextField_Arg2, jTextField_result});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PoliczActionPerformed
        try {
            String action = (String) jComboBox_action.getSelectedItem();
            
            
            double arg1 = Double.parseDouble(jTextField_Arg1.getText());
            double arg2 = Double.parseDouble(jTextField_Arg2.getText());
            
            double result = CalculatorLogic.calculation(arg1, arg2, action);
            
            jTextField_result.setText("" + result);
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this,
                    "Wrong Format", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            
            jTextField_Arg1.setText("");
            jTextField_Arg2.setText("");
        }
    }//GEN-LAST:event_jButton_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calculate;
    private javax.swing.JComboBox<String> jComboBox_action;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JTextField jTextField_Arg1;
    private javax.swing.JTextField jTextField_Arg2;
    private javax.swing.JTextField jTextField_result;
    // End of variables declaration//GEN-END:variables
}
